# Makefile for Audio-CD-Creator Data-CD-Creator

include ../make.inc

CC           = icc
LIB_DIR      = $d:/emx/lib 
CPPFLAGS     = /Ge- /Gm+ /G4 /Gl  /O+ /Oc+ /Ol- /Q+ $(VACDEBUG)
INC	=	..\include
DEFS         = 
PROGS        = 
ODIR		= 	./obj
CPPDIR	= .
BINDIR		=	../../dist
RES		=	..\res


OBJECTS	=  


all:
	cd ../creator && make

clean:
	-rm *.obj

cleaner:
	-rm *.*~
	-rm *.flc


distribution:


	
