#ifndef _DTS_HH_INCLUDED_cwaudio
#define _DTS_HH_INCLUDED_cwaudio
/* Start Class CWAudio */

// This file was generated by the IBM "DirectToSOM" emitter for C++ (V1.77)
// Generated at 02/06/02 09:53:37 EST
// This is class: CWAudio
// Mangled class name: CWAudio
// SE: May 19/94

#include <som.hh>

     #pragma SOMAsDefault(on)
class SOMClass;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class SOMObject;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class WPFolder;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class M_WPObject;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class WPObject;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class M_WPFileSystem;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class M_WPDataFile;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class M_MMDataFile;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class M_MMAudio;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class M_CWAudio;
     #pragma SOMAsDefault(pop)


/* Start Class M_CWAudio */

#include <mmaudio.hh>
#include <somcls.hh>
#pragma SOMNonDTS(on)

#pragma SOMAsDefault(on)
class M_CWAudio : public M_MMAudio {

	#pragma SOMClassName(*, "M_CWAudio")
	#pragma SOMNoMangling(*)
	#pragma SOMNonDTS(*)

     #pragma SOMClassVersion (M_CWAudio, 1, 1)
     #pragma SOMCallstyle (oidl)
     #pragma SOMAsDefault(off)
     #pragma SOMAsDefault(pop)
  public :
     virtual ULONG wpclsQueryDetailsInfo(PCLASSFIELDINFO* ppClassFieldInfo, 
                                         PULONG pSize);
     virtual PSZ wpclsQueryTitle();
     virtual void wpclsInitData();
     #pragma SOMReleaseOrder ()
};
#pragma SOMAsDefault(pop)

     #pragma SOMNonDTS(pop)
/* End M_CWAudio */


#include <mmaudio.hh>

#pragma SOMNonDTS(on)

#pragma SOMAsDefault(on)
class CWAudio : public MMAudio {

	#pragma SOMClassName(*, "CWAudio")
	#pragma SOMNoMangling(*)
	#pragma SOMNonDTS(*)

     #pragma SOMClassName (CWAudio, "CWAudio")
     #pragma SOMMetaClass (CWAudio, "M_CWAudio")
     #pragma SOMClassVersion (CWAudio, 1, 1)
     #pragma SOMCallstyle (oidl)
     #pragma SOMAsDefault(off)
     #pragma SOMAsDefault(pop)
  public :
     virtual ULONG cwmmAddWaveInformationPage(HWND hwndNotebook);
     virtual BOOL cwmmSetIdInfo(char* chrString, int iWhich);
     virtual ULONG cwmmQueryTrackInfo(char** chrString, ULONG ulSize, 
                                      int iWhich);
     virtual BOOL wpAddSettingsPages(HWND hwndNotebook);
     virtual ULONG wpQueryDetailsData(PVOID* ppDetailsData, PULONG pcp);
     virtual BOOL wpRestoreState(ULONG ulReserved);
     virtual BOOL wpSaveState();
     virtual BOOL wpModifyPopupMenu(HWND hwndMenu, HWND hwndCnr, 
                                    ULONG iPosition);
     virtual BOOL wpMenuItemSelected(HWND hwndFrame, ULONG ulMenuId);
     virtual void wpObjectReady(ULONG ulCode, WPObject* refObject);
     virtual BOOL wpRefresh(ULONG ulView, PVOID pReserved);
  private :
     ULONG ulPlaySecs;

     ULONG ulSampleRate;

     ULONG ulChannels;

     ULONG ulBPS;

     ULONG ulFileSize;

     BOOL bNeedSaving;

     char chrPlayTime[11];

     char chrSampleRate[7];

     char chrChannels[2];

     char chrBPS[3];

     char id3Name[31];

     char id3Artist[31];

     char id3Album[31];

     char id3Year[5];

     char id3Comment[31];

     char id3Genre[31];

     #pragma SOMReleaseOrder ( \
			      "cwmmAddWaveInformationPage", \
			      "cwmmSetIdInfo", \
			      "cwmmQueryTrackInfo")
};
#pragma SOMAsDefault(pop)

     #pragma SOMNonDTS(pop)
/* End CWAudio */

#endif /* _DTS_HH_INCLUDED_cwaudio */
