#define IDPB_NEXT                   105
#define IDPB_EXIT                   106
#define IDDLG_PAGE1                 100
#define IDDLG_PAGE2                 200
#define IDEF_CDRECORDPATH           201
#define IDPB_BROWSE                 203
#define IDPB_BACK                   204
#define IDEF_CDRDAOPATH             301
#define IDDLG_PAGECDRDAO            300
#define IDDLG_PAGEGRABBER           400
#define IDEF_GRABBER                401
#define IDLB_CDRDAODRIVER           302
#define IDDLG_MKISOFS               500
#define IDEF_MKISOFSPATH            501
#define IDST_CDRECORDPATH           607
#define IDDLG_MAIN                  700
#define IDST_CDRDAOPATH             602
#define IDST_GRABBERPATH            604
#define IDST_MKISOFSPATH            606
#define IDPB_FINISH                 609
#define IDSB_FIFO                   208
#define IDSB_SPEED                  210
#define IDST_OPTIONTEXT             402
#define IDDLG_FINISHPAGE            600
#define IDDLG_                      800
#define IDICO_AUDIO                 107
#define IDICO_DATA                  108

#define IDDLG_LICENCE               900
#define IDMLE_LICENCE               901
#define IDDLG_INSTRUCTION           1000
