#ifndef _DTS_HH_INCLUDED_mmaudio
#define _DTS_HH_INCLUDED_mmaudio
/* Start Class MMAudio */

// This file was generated by the IBM "DirectToSOM" emitter for C++ (V1.77)
// Generated at 02/05/02 10:04:38 EST
// This is class: MMAudio
// Mangled class name: MMAudio
// SE: May 19/94

#include <som.hh>

     #pragma SOMAsDefault(on)
class SOMClass;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class SOMObject;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class WPFolder;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class M_WPObject;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class WPObject;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class M_WPFileSystem;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class M_WPDataFile;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class M_MMDataFile;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class M_MMAudio;
     #pragma SOMAsDefault(pop)
#include <mmdataf.hh>
#pragma SOMNonDTS(on)

/* Start Class M_MMAudio */

#include <mmdataf.hh>
#include <somcls.hh>
#pragma SOMNonDTS(on)

#pragma SOMAsDefault(on)
class M_MMAudio : public M_MMDataFile {

	#pragma SOMClassName(*, "M_MMAudio")
	#pragma SOMNoMangling(*)
	#pragma SOMNonDTS(*)

     #pragma SOMClassVersion (M_MMAudio, 1, 1)
     #pragma SOMCallstyle (oidl)
     #pragma SOMAsDefault(off)
     #pragma SOMAsDefault(pop)
  public :
     virtual BOOL mmclsDeleteFromTypeList(PSZ pszType);
     virtual BOOL mmclsDeleteFromExtensionList(PSZ pszExt);
     virtual BOOL mmclsInitTypesAndExtensions();
     virtual PSZ wpclsQueryInstanceType();
     virtual PSZ wpclsQueryInstanceFilter();
     virtual void wpclsInitData();
     virtual BOOL wpclsQueryDefaultHelp(PULONG pHelpPanelId, 
                                        PSZ pszHelpLibrary);
     virtual PSZ wpclsQueryTitle();
     virtual void wpclsUnInitData();
     virtual ULONG wpclsQueryIconData(PICONINFO pIconInfo);
     #pragma SOMReleaseOrder ()
};
#pragma SOMAsDefault(pop)

     #pragma SOMNonDTS(pop)
/* End M_MMAudio */


#pragma SOMAsDefault(on)
class MMAudio : public MMDataFile {

	#pragma SOMClassName(*, "MMAudio")
	#pragma SOMNoMangling(*)
	#pragma SOMNonDTS(*)

     #pragma SOMClassName (MMAudio, "MMAudio")
     #pragma SOMMetaClass (MMAudio, "M_MMAudio")
     #pragma SOMClassVersion (MMAudio, 1, 1)
     #pragma SOMCallstyle (oidl)
     #pragma SOMAsDefault(off)
     #pragma SOMAsDefault(pop)
  public :
     virtual ULONG mmFilterPopupMenu(ULONG ulFlags, HWND hwndcnr, 
                                     BOOL fMultiSelect);
     virtual ULONG mmViewNotify();
     virtual BOOL wpFormatDragItem(PDRAGITEM pdrgItem);
     virtual BOOL wpMenuItemSelected(HWND hwndFrame, ULONG ulMenuId);
     virtual BOOL wpModifyPopupMenu(HWND hwndMenu, HWND hwndCnr, 
                                    ULONG iPosition);
     virtual HWND wpOpen(HWND hwndCnr, ULONG ulView, ULONG param);
     virtual ULONG wpQueryDefaultView();
     virtual void wpUnInitData();
     #pragma SOMReleaseOrder ()
};
#pragma SOMAsDefault(pop)

     #pragma SOMNonDTS(pop)
/* End MMAudio */

#endif /* _DTS_HH_INCLUDED_mmaudio */
