#ifndef _DTS_HH_INCLUDED_mmdataf
#define _DTS_HH_INCLUDED_mmdataf
/* Start Class MMDataFile */

// This file was generated by the IBM "DirectToSOM" emitter for C++ (V1.77)
// Generated at 02/05/02 10:05:05 EST
// This is class: MMDataFile
// Mangled class name: MMDataFile
// SE: May 19/94

#include <som.hh>

     #pragma SOMAsDefault(on)
class SOMClass;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class SOMObject;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class WPFolder;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class M_WPObject;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class WPObject;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class M_WPFileSystem;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class M_WPDataFile;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class M_MMDataFile;
     #pragma SOMAsDefault(pop)
#include <wpdataf.hh>
#pragma SOMNonDTS(on)


/* Start Class M_MMDataFile */

#include <wpdataf.hh>
#include <somcls.hh>
#pragma SOMNonDTS(on)

#pragma SOMAsDefault(on)
class M_MMDataFile : public M_WPDataFile {

	#pragma SOMClassName(*, "M_MMDataFile")
	#pragma SOMNoMangling(*)
	#pragma SOMNonDTS(*)

     #pragma SOMClassVersion (M_MMDataFile, 1, 1)
     #pragma SOMCallstyle (oidl)
     #pragma SOMAsDefault(off)
     #pragma SOMAsDefault(pop)
  public :
     virtual BOOL mmclsDeleteFromTypeList(PSZ pszType);
     virtual BOOL mmclsDeleteFromExtensionList(PSZ pszExt);
     virtual BOOL mmclsInitTypesAndExtensions();
     virtual BOOL mmclsSetDefaultView(ULONG ulView);
     virtual PSZ wpclsQueryInstanceType();
     virtual PSZ wpclsQueryInstanceFilter();
     virtual BOOL wpclsCreateDefaultTemplates(WPObject* Folder);
     virtual void wpclsInitData();
     virtual BOOL wpclsQueryDefaultHelp(PULONG pHelpPanelId, 
                                        PSZ pszHelpLibrary);
     virtual ULONG wpclsQueryDefaultView();
     virtual ULONG wpclsQueryStyle();
     virtual PSZ wpclsQueryTitle();
     virtual void wpclsUnInitData();
     virtual ULONG wpclsQueryIconData(PICONINFO pIconInfo);
     #pragma SOMReleaseOrder ( \
			      "mmclsDeleteFromTypeList", \
			      "mmclsDeleteFromExtensionList", \
			      "mmclsInitTypesAndExtensions", \
			      "mmclsSetDefaultView")
};
#pragma SOMAsDefault(pop)

     #pragma SOMNonDTS(pop)
/* End M_MMDataFile */


#pragma SOMAsDefault(on)

class MMDataFile : public WPDataFile {

	#pragma SOMClassName(*, "MMDataFile")
	#pragma SOMNoMangling(*)
	#pragma SOMNonDTS(*)

     #pragma SOMClassName (MMDataFile, "MMDataFile")
     #pragma SOMMetaClass (MMDataFile, "M_MMDataFile")
     #pragma SOMClassVersion (MMDataFile, 1, 1)
     #pragma SOMCallstyle (oidl)
     #pragma SOMAsDefault(off)
     #pragma SOMAsDefault(pop)
  public :
     virtual ULONG mmFilterPopupMenu(ULONG ulFlags, HWND hwndcnr, 
                                     BOOL fMultiSelect);
     virtual ULONG mmViewNotify();
     virtual ULONG mmDetermineViewFor();
     virtual ULONG wpFilterPopupMenu(ULONG ulFlags, HWND hwndCnr, 
                                     BOOL fMultiSelect);
     virtual void wpInitData();
     virtual BOOL wpMenuItemHelpSelected(ULONG MenuId);
     virtual BOOL wpMenuItemSelected(HWND hwndFrame, ULONG ulMenuId);
     virtual BOOL wpModifyPopupMenu(HWND hwndMenu, HWND hwndCnr, 
                                    ULONG iPosition);
     virtual HWND wpOpen(HWND hwndCnr, ULONG ulView, ULONG param);
     virtual ULONG wpQueryConcurrentView();
     virtual ULONG wpQueryDefaultView();
     virtual BOOL wpSetTitle(PSZ pszNewTitle);
     virtual BOOL wpSetup(PSZ pszSetupString);
     virtual void wpUnInitData();
     virtual void wpObjectReady(ULONG ulCode, WPObject* refObject);
  private :
     ULONG ul1;

     ULONG ul2;

     ULONG ul3;

     #pragma SOMReleaseOrder ( \
			      "mmFilterPopupMenu", \
			      "mmViewNotify", \
			      "mmDetermineViewFor")
};
#pragma SOMAsDefault(pop)

     #pragma SOMNonDTS(pop)
/* End MMDataFile */

#endif /* _DTS_HH_INCLUDED_mmdataf */
