#ifndef _DTS_HH_INCLUDED_wppgm
#define _DTS_HH_INCLUDED_wppgm
/* Start Class WPProgram */

// This file was generated by the IBM "DirectToSOM" emitter for C++ (V1.77)
// Generated at 10/22/96 06:19:25 EDT
// This is class: WPProgram
// Mangled class name: WPProgram
// SE: May 19/94

#include <som.hh>

     #pragma SOMAsDefault(on)
class SOMClass;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class SOMObject;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class WPFolder;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class M_WPObject;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class WPObject;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class M_WPAbstract;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class M_WPProgram;
     #pragma SOMAsDefault(pop)
#include <wpabs.hh>
#pragma SOMNonDTS(on)

#pragma SOMAsDefault(on)
class WPProgram : public WPAbstract {

	#pragma SOMClassName(*, "WPProgram")
	#pragma SOMNoMangling(*)
	#pragma SOMNonDTS(*)

     #pragma SOMClassName (WPProgram, "WPProgram")
  //   #pragma SOMMetaClass (WPProgram, "M_WPProgram")
     #pragma SOMClassVersion (WPProgram, 1, 2)
     #pragma SOMCallstyle (oidl)
     #pragma SOMAsDefault(off)
     #pragma SOMAsDefault(pop)
  public :
     virtual ULONG wpAddProgramAssociationPage(HWND hwndNotebook);
     virtual BOOL wpQueryProgDetails(PPROGDETAILS pProgDetails, 
                                     PULONG pulSize);
     virtual BOOL wpSetProgDetails(PPROGDETAILS pProgDetails);
     virtual ULONG wpAddProgramPage(HWND hwndNotebook);
     virtual ULONG wpAddProgramSessionPage(HWND hwndNotebook);
     virtual PSZ wpQueryAssociationFilter();
     virtual PSZ wpQueryAssociationType();
     virtual BOOL wpSetAssociationFilter(PSZ pszFilter);
     virtual BOOL wpSetAssociationType(PSZ pszType);
     virtual PSZ wpQueryProgramAssociations(PBYTE ptr, PSZ pszAssoc, 
                                            BOOL fFilter);
     virtual BOOL wpSetProgramAssociations(PSZ pszAssoc, BOOL fFilter);
     virtual BOOL wpSetProgIcon(PFEA2LIST pfeal);
     virtual BOOL wpQueryDefaultHelp(PULONG pHelpPanelId, PSZ HelpLibrary);
     virtual void wpInitData();
     virtual BOOL wpSetup(PSZ pszSetupString);
     virtual void wpUnInitData();
     virtual BOOL wpSaveState();
     virtual BOOL wpRestoreState(ULONG ulReserved);
     virtual BOOL wpAddSettingsPages(HWND hwndNotebook);
     virtual HWND wpOpen(HWND hwndCnr, ULONG ulView, ULONG param);
     virtual BOOL wpModifyPopupMenu(HWND hwndMenu, HWND hwndCnr, 
                                    ULONG iPosition);
     virtual BOOL wpMenuItemSelected(HWND hwndFrame, ULONG ulMenuId);
     virtual BOOL wpMenuItemHelpSelected(ULONG MenuId);
     virtual WPObject* wpCreateFromTemplate(WPFolder* folder, 
                                            BOOL fLock);
     virtual WPObject* wpCreateAnother(PSZ pszTitle, PSZ pszSetupEnv, 
                                       WPFolder* Folder);
     virtual ULONG wpQueryIconData(PICONINFO pIconInfo);
     virtual BOOL wpSetIconData(PICONINFO pIconInfo);
     virtual HPOINTER wpQueryIcon();
     virtual BOOL wpMoveObject(WPFolder* Folder);
     virtual WPObject* wpCopyObject(WPFolder* Folder, BOOL fLock);
     virtual MRESULT wpDragOver(HWND hwndCnr, PDRAGINFO pdrgInfo);
     virtual MRESULT wpDrop(HWND hwndCnr, PDRAGINFO pdrgInfo, 
                            PDRAGITEM pdrgItem);
     virtual BOOL wpSetTitle(PSZ pszNewTitle);
     #pragma SOMReleaseOrder ( \
			      "wpAddProgramPage", \
			      "wpAddProgramSessionPage", \
			      "wpQueryProgDetails", \
			      "wpSetProgDetails", \
			      *, \
			      *, \
			      "wpAddProgramAssociationPage", \
			      "wpSetProgIcon", \
			      "wpQueryAssociationFilter", \
			      "wpQueryAssociationType", \
			      "wpSetAssociationFilter", \
			      "wpSetAssociationType", \
			      "wpQueryProgramAssociations", \
			      "wpSetProgramAssociations")
};
#pragma SOMAsDefault(pop)

     #pragma SOMNonDTS(pop)
/* End WPProgram */
/* Start Class M_WPProgram */

#include <wpabs.hh>
#include <somcls.hh>
#pragma SOMNonDTS(on)

#pragma SOMAsDefault(on)
class M_WPProgram : public M_WPAbstract {

	#pragma SOMClassName(*, "M_WPProgram")
	#pragma SOMNoMangling(*)
	#pragma SOMNonDTS(*)

     #pragma SOMClassVersion (M_WPProgram, 1, 2)
     #pragma SOMCallstyle (oidl)
     #pragma SOMAsDefault(off)
     #pragma SOMAsDefault(pop)
  public :
     virtual PSZ wpclsQueryTitle();
     virtual ULONG wpclsQueryIconData(PICONINFO pIconInfo);
     virtual ULONG wpclsQueryStyle();
     virtual BOOL wpclsQueryDefaultHelp(PULONG pHelpPanelId, 
                                        PSZ pszHelpLibrary);
     virtual ULONG wpclsQueryDefaultView();
     #pragma SOMReleaseOrder ()
};
#pragma SOMAsDefault(pop)

     #pragma SOMNonDTS(pop)
/* End M_WPProgram */
#endif /* _DTS_HH_INCLUDED_wppgm */
