:h1 res=300
x=left y=bottom
width=35%
height=100%
group=1.Advanced installation
:link reftype=hd res=303 auto dependent.

:p.With V0.39 of the classes it's possible to keep the settings of a previous installation. 
Select the appropriate link below for more information.
:p.
:link reftype=hd res=303.Prerequisites.:elink.
:p.
:link reftype=hd res=301.First time installation.:elink.
:p.
:link reftype=hd res=302.Upgrade from an older version:elink.
:p.
:link reftype=hd res=304.Using the first time:elink.

.im prerequisites.inc
.im firsttimeinstallation.inc
.im upgradeinstallation.inc
.im firsttimeusage.inc
