:h2 res=406
x=right y=bottom
width=65%
height=100%
group=2. Create a copy of a cd
:i1.1&colon.1 copy
:ol.
:li.To burn a simple 1&colon.1 copy of a CD use the :hp2.1&colon.1 CD-Copy:ehp2. object.
:li.To work CDRDAO must be installed.
:li.The source drive and target drive, as the driver information, are pulled 
from :hp2.Cd-Creator Settings:ehp2. on the :hp2.cdrdao/2:ehp2. page 2 (source) and 3 (target), so make sure you 
have selected the correct driver(s).
:artwork name='pmaudcpy.bmp'.
:li.Select from 'Action' :hp2.Copy CD:ehp2..
:li.Either uncheck :hp2.Test only:ehp2. for performing the copy, or let it checked for a Test.
:li.Select the :hp2.Drive for raw image:ehp2. - the drive where the image should be stored - from the dropdownlist. The drive should have at least min. 640Mbytes free space.
:li.Press :hp2.ok:ehp2. to perform the action or :hp2.cancel:ehp2. to abort.  All image-files will be 
deleted after a successful copy.
:li.You can too generate an image of the CD by selecting the button :hp2.Grab image:ehp2. from the 
'Action' list. Then select the driveletter and the name of the image in :hp2.Image file destination:ehp2.. E.g&colon. 
F&colon.\test.bin. In this case the test.bin and test.TOC (table of content) are stored at your drive F&colon. 
for reuse.
:li.To burn a stored image select :hp2.Write raw image:ehp2. from 'Action' and insert in :hp2.Source image:ehp2. 
the place where the image and the TOC-file is stored and it's name, e.g&colon. F&colon.\test.TOC. 
:eol.