:h2 res=406
x=right y=bottom
width=65%
height=100%
group=2. Create an copy of an audio cd
:i1.1&colon.1 copy
:ol.
:li.To burn a simple 1&colon.1 copy of an audio CD use the seperate PMAUDCPY.EXE.
:li.To work CDRDAO must be installed.
:artwork name='pmaudcpy.bmp'.
:li.Select your CD-Player as Source and your CD-Recorder as Target drive.
:li.If you have only a CD-Recorder select it as Source and as Target drive. 
:li.Select the drive where the image should be stored. The drive should have at least 
min. 640Mbytes free space
:li.Either uncheck 'Test only' for performing the copy, or let it checked for a Test.
:li. Press 'ok' to perform the action or 'cancel' to abort.
:eol.