:h2 res=1300.FreeDB setup
:p.
Configure FreeDB on this page. FreeDB is a free internet based service
which provides the information about the tracknames of an inserted CD.

:nt.The current implementation does not support proxies.
This means you must have a direct connection to the internet.:ent.

Get more information by clicking on the links:
:sl.
:li.:link reftype=hd res=1302.Use FreeDB:elink.
:li.:link reftype=hd res=1304.Your e-mail address:elink.
:li.:link reftype=hd res=1301.Undo:elink.
:esl.
:p.
:nt.
If you enable :hp2.Show all settings:ehp2. on the first page another
FreeDB page will be shown on which you may configure the used servers.
:ent.

:h3 res=1302. Use FreeDB
:p.
Click on this Button to enable the use of FreeDB.
Make sure to specify an e-mail address or the FreeDB query will
not succeed.

:h3 res=1304.Your e-mail address
:p.
To use the FreeDB service an e-mail address must be sent to the FreeDB server.
Enter your address into this field.

:h3 res=1301.Undo
:p.
Click on this button to discard the changes you've made.


:h2 res=1307.FreeDB server setup
:p.
If you decide not to use the already configured FreeDB you have to insert 
here the servers and the ports to access the FreeDB information (e.g. 
de.freedb.org&colon.888 for the german freedb mirror on port 888).
.*You can also adda News Server e.g. news.cis.dfn.de. Get an account here http&colon.//news.cis.dfn.de/
:p.
If a server does not deliver the requested information, the next server in the
list will be queried. So if you have a preferred server put it at the top of the list.





