:h2 res=300.CDRecord/2 setup

Configure CDRecord/2 on this page. CDRecord/2 is the program which actually writes the CD.
Mandatory is the program path. Usually it's not necessary to include any options here.
The changes take effect after closing of the notebook.
:p.
Get more information by clicking on the links:
:sl.
:li.:link reftype=hd res=302.Path:elink.	
:li.:link reftype=hd res=303.Browse:elink.
:li.:link reftype=hd res=306.Options:elink.
:li.:link reftype=hd res=301.Undo:elink.
:esl.

:h3 res=301.Undo
:p.
Click on this button to discard the changes you've made.

:h3 res=302.Path
:p.
Enter the path to CDRecord/2 into this entryfield or use the :link reftype=hd res=303.Browse:elink. button
to find the executable.

:h3 res=303.Browse
:p.
Use this button to find the executable of CDRecord/2. A filedialog will pop up helping you browsing your
disks.

:h3 res=306.Options
:p.
Enter arbitrary options into these entryfields to customize your 
CDRecord/2 commandline. Only options not accessible on the main 
window or the 'General' settings page should be entered here. 
:p.
Note that CDRecord/2 is used to write data CDs and to write audio CDs in TAO (track at once) mode.
So there're two fields for data CD options and those for audio CDs.
  