:h2 res=701
x=right y=bottom
width=65%
height=100%
group=2. List of known CD-Writers
:p.
Supported drives with cdrecord-1.10: 
:p.
Cdrecord should work with: 
:p.
:hp2.All SCSI-3/mmc compliant drives 
:p.
All ATAPI/mmc compliant drvies:ehp2.
:p.
It seems that all drives that have been initially released in 1999 or later are MMC compliant. 
:p.
If a recent drive does not work with cdrecord, you most likely found a firmware bug. 
:p.
:nt.A List of Firmwareupgrades for your Recorder can be found at:ent.
:link reftype=launch
object='netscape.exe'
data='http://www.firmware.fr.st/'.
http&colon.//www.firmware.fr.st/:elink.
   
:p.
:hp2.Drives that have been reported to work or that should work:ehp2.
:sl compact.
:li.ACER CR-1420C 
:li.ACER CDRW 6206A 
:li.AOPEN CRW9420 (Re-writeable) 
:li.BTC BCE 621E 
:li.COMPRO/Matsushita/Panasonic CW-7502 
:li.Dysan CR-622 ???? See Wearnes 622 
:li.Dysan CR-1622 
:li.DynaTec CDM-240J (see Pinnacle RCD-4x4) 
:li.DynaTec CDM-240 (use cdrecord driver=yamaha_cdr100 and report inquiry) 
:li.DynaTec CDM-400 (use cdrecord driver=yamaha_cdr100 and report inquiry) 
:li.Goldstar 8080 
:li.Freecom Traveller 
:li.Grundig CDR-100 
:li.Hewlett Packard 4020i 
:li.Hewlett Packard 6020i 
:li.HP C4324/C4325 (HP SureStore 4020i/6020i) 
:li.HP 7100 
:li.HP 7110 
:li.HP 7200 
:li.HP 8100 
:li.HP 8210 
:li.HP 9100/9200 
:li.HP 9300i 
:li.HP CD-Writer+ M820 
:li.Hi-Val CD-R (see Pinnacle RCD-4x4) 
:li.IMATION CD-RW IMW040420 
:li.JVC XR-W2001 (uses TEAC code - see below and this page - audio not working) 
:li.JVC XR-W2010 (uses TEAC code - see below and this page - audio not working) 
:li.JVC XR-W2020 (uses TEAC code - see below and this page - audio not working) 
:li.JVC XR-W2080 (first MMC drive from JVC) 
:li.Kodak PCD-200 or Kodak PCD-200 Plus 
:li.Kodak PCD-225 
:li.Kodak PCD-240 
:li.Kodak PCD-600 
:li.Matsushita CW-7502 
:li.Matsushita CW-7503 
:li.Matsushita CW-7582 
:li.Memorex CR-622 ???? See Wearnes 622 
:li.Memorex CR-1622 
:li.Memorex CRW-1622 
:li.Microboards PlayWrite 2000 (use cdrecord driver=sony_cdu924 and report inquiry) 
:li.Microboards PlayWrite 4000 (use cdrecord driver=yamaha_cdr100 and report inquiry) 
:li.Microboards PlayWrite 4001RW 
:li.MicroNet MasterCD Plus 4x4 (use cdrecord driver=yamaha_cdr100 and report inquiry) 
:li.MicroNet MasterCD Plus 4x6 
:li.Mitsubishi MCA-CDRW 226 
:li.Mitsubishi DD6430A 
:li.Mitsumi CR-2401-TS 
:li.Mitsumi CR-2600-TE 
:li.Mitsumi CR-2801-TE 
:li.Mitsumi CR-4801-TE 
:li.Mitsumi CR-4802-TE ??? 
:li.Nomai 680.rw 
:li.Olympus CDS615E 
:li.Olympus CDS620E (use cdrecord driver=sony_cdu924 and report inquiry) 
:li.Olympus CD-R2x6 (use cdrecord driver=sony_cdu924 and report inquiry) 
:li.Optima Dis Kovery 650 CD-R 
:li.OTI CDRW 965 
:li.OTI-975 Socrates 1.0 (CDRW) 
:li.Panasonic CW-7502 
:li.Panasonic CW-7503 
:li.Panasonic CW-7582 
:li.Philips CDD 521 (CDD521/02 Revision: 2.06 has bad firmware - seems not to work) 
:li.Philips CDD 521 (upgraded units only: ID: CDD521/10 Revision: 2.07) 
:li.Philips CDD 522 
:li.Philips CDD 2000 
:li.Philips CDD 2600 
:li.Philips CDD 3600 
:li.Philips CDD 3610 
:li.Philips CDRW400 
:li.Philips Omniwriter 26 
:li.Philips Omniwriter 26A 
:li.Philips CDD4201 CD-RW 
:li.Pinnacle Micro RCD-1000 (see TEAC/JVC): Need to upgrade firmware to 2.35 
:li.Pinnacle Micro RCD-5020 (see TEAC/JVC - audio not working) 
:li.Pinnacle Micro RCD-5040 (see TEAC/JVC - audio not working) 
:li.Pinnacle Micro RCD-4x4 
:li.Pioneer DW-S114X 
:li.Plasmon CDR 4220 
:li.Plasmon RF-4100 (Multi-session has not been tested) 
:li.Plasmon RF-4102 
:li.Plasmon CDR 4400 (use cdrecord driver=yamaha_cdr100 and report inquiry) 
:li.Plasmon CDR 480 
:li.Plextor PX-W124 
:li.Plextor PX-W8220 
:li.Plextor PX-W4220 
:li.Plextor PX-R820 
:li.Plextor PX-R412C 
:li.Plextor PX-R820 
:li.Plextor PX-R24CS (use cdrecord driver=ricoh_ro1420c and report inquiry) 
:li.Plextor PX-W1210TA (with BURN-Proof) 
:li.Plextor PX-W241040A
:li.Plextor PX-W121032S
:li.Plextor PX-W121032A
:li.Plextor PX-W161032A
:li.Procom PCDR 4 (use cdrecord driver=yamaha_cdr100 and report inquiry) 
:li.Ricoh MP-7040A 
:li.Ricoh MP-7040S 
:li.Ricoh MP-7060S 
:li.Ricoh RO-1420C 
:li.Ricoh MP-6200 
:li.Ricoh MP-6200I 
:li.Ricoh MP-6201 
:li.Ricoh 9060 CD-RW/DVD-ROM drive 
:li.SAMSUNG SW-206 
:li.Sanyo CDR-Bp2 (with BURN-Proof) 
:li.Sanyo CD-WO CRD-R24S 
:li.Smart &amp.  Friendly CD-R1002 (use cdrecord driver=sony_cdu924 and report inquiry) 
:li.Smart &amp.  Friendly CD-R1004 (use cdrecord driver=yamaha_cdr100 and report inquiry) 
:li.Smart &amp.  Friendly CD-R2004 (use cdrecord driver=sony_cdu924 and report inquiry) 
:li.Smart &amp.  Friendly CD-R2006 PLUS 
:li.Smart &amp.  Friendly CD-R2006 PRO 
:li.Smart &amp.  Friendly CD-R4000 (use cdrecord driver=yamaha_cdr100 and report inquiry) 
:li.Smart &amp.  Friendly CD-R4006 
:li.Smart &amp.  Friendly CD-R4012 
:li.Smart &amp.  Friendly CD-RW226 
:li.Smart &amp.  Friendly CD-R8020 
:li.Sony CDU920S 
:li.Sony CDU924S 
:li.Sony CDU926S 
:li.Sony CDU928S 
:li.Sony CDU940S 
:li.Sony CDU948S 
:li.Sony CRX-100 
:li.Sony CRX-140S 
:li.Sony CRX-140E 
:li.Sony CRX-145E 
:li.Taiyo Yuden CD-WO EW-50 
:li.TEAC CD-R50S 
:li.TEAC CD-R55S 
:li.TEAC CD-R56S 
:li.TEAC CD-R58S 
:li.TEAC CD-R58S 
:li.TEAC CD-W54E
:li.That's Write CDR-N820S 
:li.Traxdata CDRW-2260EL-PRO 
:li.Traxdata CDR-4120 
:li.Traxdata CDRW-4260 
:li.Turtle Beach 2040R (use cdrecord driver=ricoh_ro1420c and report inquiry) 
:li.WAITEK WT2036 
:li.Wearnes CD-R622 
:li.Wearnes CD-R632P 
:li.Yamaha CDR-100 
:li.Yamaha CDR-102 
:li.Yamaha CDR-200 
:li.Yamaha CDR-400(Firmware revision 1.0d and up otherwise upgrade) 
:li.Yamaha CDR-401 
:li.Yamaha CRW-4001 
:li.Yamaha CRW-2260 
:li.Yamaha CRW-2261 
:li.Yamaha CRW-4260 
:li.Yamaha CRW-4261 
:li.Yamaha CRW-4416 
:li.Yamaha CRW-6416 
:li.Yamaha CRW-8424
:li.Yahama CRW-8832
:li.Yahama CRW-2100
:li.Yahama CRW-2200
:esl.
:p.  
:hp2.Unsupported Drives:ehp2.

:sl compact.
:li.Creative Labs CDR 
:li.JVC XR-W1001 
:li.JVC XR-W2001 
:li.JVC XR-W2010 
:li.Panasonic CW-7501 
:li.Pinnacle MicroRCD-202 
:li.Pinnacle MicroRCD-1000 
:li.Pinnacle MicroRCD-5020 
:li.Pinnacle MicroRCD-5040 
:li.Plasmon CDR-4240 
:li.Ricoh RS-1060C 
:li.Ricoh RS-9200C 
:li.Sony CDW-900E 
:esl.
:p.
:p.  
:hp2.Driver table for cdrdao-1.1.4:ehp2.
:p.
:nt.For more information got to :ent.
:link reftype=launch
object='netscape.exe'
data='http://cdrdao.sourceforge.net/drives.html'.
http&colon.//cdrdao.sourceforge.net/drives.html:elink.
:p.

:hp2.Drivers for read operations:ehp2.
:sl compact.
:li.ASUS CD-S340|generic-mmc
:li.ASUS CD-S400|generic-mmc
:li.E-IDE CD-ROM 36X/AKU|generic-mmc
:li.HITACHI CDR-8435|generic-mmc|OPT_MMC_NO_SUBCHAN
:li.HITACHI DVD-ROM GD-2500|plextor
:li.KENWOOD UCR-415|generic-mmc|OPT_DRV_GET_TOC_GENERIC
:li.LG CRD-8480C|generic-mmc|OPT_MMC_NO_SUBCHAN
:li.LITEON CD-ROM|generic-mmc|OPT_DRV_GET_TOC_GENERIC
:li.MATSHITA CR-588|generic-mmc
:li.MATSHITA CD-ROM CR-506|plextor|OPT_PLEX_DAE_D4_12
:li.MEMOREX CD-233E|generic-mmc
:li.PHILIPS PCCD052|generic-mmc
:li.PHILIPS E-IDE CD-ROM 36X|generic-mmc
:li.NAKAMICH MJ-5.16S|plextor
:li.PIONEER DR-U32|generic-mmc|OPT_DRV_GET_TOC_GENERIC|OPT_MMC_USE_PQ|OPT_MMC_PQ_BCD
:li.PIONEER DVD-103|generic-mmc|OPT_MMC_USE_PQ|OPT_MMC_PQ_BCD
:li.PIONEER DVD-104|generic-mmc|OPT_MMC_USE_PQ|OPT_MMC_PQ_BCD
:li.PIONEER DVD-105|generic-mmc|OPT_MMC_USE_PQ|OPT_MMC_PQ_BCD
:li.PIONEER DR-U03|plextor|OPT_DRV_GET_TOC_GENERIC
:li.PIONEER DR-U06|plextor|OPT_DRV_GET_TOC_GENERIC
:li.PIONEER DR-U10|plextor|OPT_DRV_GET_TOC_GENERIC
:li.PIONEER DR-U12|plextor|OPT_DRV_GET_TOC_GENERIC
:li.PIONEER DR-U16|plextor|OPT_DRV_GET_TOC_GENERIC
:li.PIONEER DVD-303|plextor
:li.PLEXTOR CD-ROM|plextor-scan
:li.SAF CD-R2006PLUS|plextor
:li.SONY CD-ROM|plextor
:li.SONY CDU-76|plextor
:li.SONY CDU31A-02|generic-mmc
:li.SONY CDU4821|generic-mmc
:li.TEAC CD-532S|plextor-scan|OPT_PLEX_USE_PQ|OPT_PLEX_PQ_BCD
:li.TEAC CD-524E|generic-mmc|OPT_DRV_GET_TOC_GENERIC
:li.TEAC CD-532E|generic-mmc|OPT_MMC_USE_PQ|OPT_MMC_PQ_BCD
:li.TEAC CD-540E|generic-mmc|OPT_MMC_USE_PQ|OPT_MMC_PQ_BCD
:li.TOSHIBA XM-3206B|generic-mmc
:li.TOSHIBA XM-6302B|generic-mmc
:li.TOSHIBA XM-5401|plextor
:li.TOSHIBA XM-5701TA|toshiba
:li.TOSHIBA XM-6201TA|toshiba
:li.TOSHIBA XM-6401TA|toshiba
:esl.
:p.
:hp2.Drivers for write operations:ehp2.
:sl compact.
:li.AOPEN CRW9624|generic-mmc
:li.ATAPI CD-R/RW 4X4X32|generic-mmc-raw
:li.ATAPI CD-R/RW CRW6206A|generic-mmc-raw
:li.BTC BCE621E|generic-mmc-raw
:li.GENERIC CRD-RW2|generic-mmc
:li.HP CD-Writer 4020|cdd2600
:li.HP CD-Writer 6020|cdd2600
:li.HP CD-Writer+ 7570|generic-mmc|OPT_MMC_CD_TEXT
:li.HP CD-Writer+ 8100|generic-mmc|OPT_MMC_CD_TEXT
:li.HP CD-Writer+ 8200|generic-mmc|OPT_MMC_CD_TEXT
:li.HP CD-Writer+ 9100|generic-mmc|OPT_MMC_CD_TEXT
:li.HP CD-Writer+ 9200|generic-mmc|OPT_MMC_CD_TEXT
:li.HP CD-Writer+ 9300|generic-mmc|OPT_MMC_CD_TEXT
:li.HP CD-Writer+ 7100|generic-mmc-raw
:li.HP CD-Writer+ 7200|generic-mmc-raw
:li.IMS CDD2000|cdd2600
:li.IDE-CD R/RW 2x2x24|generic-mmc-raw
:li.IDE-CD ReWritable-2x2x6|generic-mmc-raw
:li.IOMEGA ZIPCD 4x650|generic-mmc-raw
:li.JVC R2626|teac-cdr55
:li.JVC XR-W2010|teac-cdr55
:li.KODAK PCD-225|cdd2600
:li.LG CD-RW CED-8080B|generic-mmc
:li.MATSHITA CW-7502|generic-mmc
:li.MATSHITA CW-7503|generic-mmc
:li.MATSHITA CW-7582|generic-mmc
:li.MATSHITA CW-7585|generic-mmc
:li.MATSHITA CDRRW01|generic-mmc
:li.MEMOREX CD-RW4224|generic-mmc
:li.MEMOREX CDRW-2216|generic-mmc-raw
:li.MEMOREX CR-622|generic-mmc-raw
:li.MEMOREX CRW-1662|generic-mmc-raw
:li.MITSUMI 2801|generic-mmc-raw
:li.MITSUMI CR-4802|generic-mmc-raw
:li.MITSUMI CR-4801|generic-mmc
:li.PANASONIC CD-R   CW-7582|generic-mmc
:li.PHILIPS PCA460RW|generic-mmc
:li.PHILIPS CDD2000|cdd2600
:li.PHILIPS CDD2600|cdd2600
:li.PHILIPS CDD522|cdd2600
:li.PHILIPS CDD3600|generic-mmc-raw
:li.PHILIPS CDD3610|generic-mmc-raw
:li.PHILIPS PCRW404|generic-mmc-raw
:li.PHILIPS OMNIWRITER26|ricoh-mp6200
:li.PLEXTOR PX-R412|generic-mmc|OPT_MMC_USE_PQ|OPT_MMC_READ_ISRC
:li.PLEXTOR PX-R820|generic-mmc
:li.PLEXTOR PX-W124|generic-mmc
:li.PLEXTOR PX-W4220|generic-mmc|OPT_MMC_CD_TEXT
:li.PLEXTOR PX-W8220|generic-mmc|OPT_MMC_CD_TEXT
:li.PLEXTOR PX-W8432|generic-mmc|OPT_MMC_CD_TEXT
:li.PLEXTOR W1210A|generic-mmc|OPT_MMC_CD_TEXT
:li.RICOH MP7060|generic-mmc|OPT_MMC_CD_TEXT
:li.RICOH MP7080|generic-mmc|OPT_MMC_CD_TEXT
:li.RICOH DVD/CDRW MP9060|generic-mmc|OPT_MMC_CD_TEXT
:li.RICOH MP6200|ricoh-mp6200
:li.RICOH MP6201|ricoh-mp6200
:li.SAF CD-R 8020|generic-mmc
:li.SAF CD-RW6424|generic-mmc
:li.SAF CD-R2006PLUS|teac-cdr55
:li.SAF CD-R4012|teac-cdr55
:li.SAF CD-RW 226|teac-cdr55
:li.SAMSUNG CD-R/RW SW-206|generic-mmc
:li.SONY CRX100|generic-mmc|OPT_MMC_CD_TEXT
:li.SONY CRX120|generic-mmc|OPT_MMC_CD_TEXT
:li.SONY CRX140|generic-mmc|OPT_MMC_CD_TEXT
:li.SONY CDU920|sony-cdu920
:li.SONY CDU924|sony-cdu920
:li.SONY CDU948|sony-cdu948
:li.TEAC CD-R56|generic-mmc|OPT_MMC_USE_PQ|OPT_MMC_CD_TEXT
:li.TEAC CD-R58|generic-mmc|OPT_MMC_USE_PQ|OPT_MMC_CD_TEXT
:li.TEAC CD-W54E|generic-mmc
:li.TEAC CD-R50|teac-cdr55
:li.TEAC CD-R55|teac-cdr55
:li.TRAXDATA CDRW4260|generic-mmc
:li.TRAXDATA CDRW2260+|generic-mmc-raw
:li.TRAXDATA CRW2260 PRO|generic-mmc-raw
:li.TRAXDATA CDR4120|teac-cdr55
:li.T.YUDEN CD-WO EW-50|taiyo-yuden
:li.WAITEC WT624|generic-mmc
:li.WAITEC WT2444EI|generic-mmc-raw
:li.WAITEC WT4424|generic-mmc-raw
:li.YAMAHA CDR200|generic-mmc
:li.YAMAHA CDR400|generic-mmc
:li.YAMAHA CRW2260|generic-mmc
:li.YAMAHA CRW4001|generic-mmc
:li.YAMAHA CRW4260|generic-mmc
:li.YAMAHA CRW4416|generic-mmc
:li.YAMAHA CRW6416|generic-mmc
:li.YAMAHA CRW8424|generic-mmc
:li.YAMAHA CRW8824|generic-mmc|OPT_MMC_CD_TEXT
:li.YAMAHA CDR100|yamaha-cdr10x
:li.YAMAHA CDR102|yamaha-cdr10x
:esl.