:h2 res=852
x=right y=bottom
width=65%
height=100%
group=2.Extended context menu
:i2 refid=customization.Extended context menu
:i1.Extended context menu
:p.
If you've installed WPS-Wizard you may configure your own context menu for the
creator classes. Get this WPS extension from the following location.

:p. 
:link reftype=launch
object='netscape.exe'
data='http://www.geocities.com/SiliconValley/Sector/5785/index.html'.
http&colon.//www.geocities.com/SiliconValley/Sector/5785/index.html:elink.
.br
:link reftype=launch
object='netscape.exe'
data='http://www.os2world.com/cdwriting'.
http&colon.//www.os2world.com/cdwriting/:elink.

:nt.If WPS-Wizard isn't installed when installing Audio/Data-Cd-Creator
an object is created to add the necessary configuration folders later.:ent. 

:p.
Open the :hp2.Configuration and (Un)Installation:ehp2. folder in the
:hp2.CD-Writing:ehp2. folder to find the configuration folder for the
context menu. Customize the context menu as described in the tutorial coming
with WPS-Wizard.

