:p.
If you still have problems after reading this tutorial twice you may
contact me via E-mail:
:p.
:hp2.chris.wohlgemuth[at]cityweb.de:ehp2.
:p.
:p.
Include the following information:
:ul.
:li.Version of the classes.
:li.OS/2 version and fixpack level.
:li.CDrecord/2 and mkisofs version.
:li.Which writer you're using.
:li.SCSI or ATAPI writer.
:li.All steps to reproduce a problem.
:li.The logfiles from the logfiles directory.
:li.Your config.sys if you've install problems.
:eul.
:p.
Without that information there's no way to solve a problem!



