:h2 res=854
x=right y=bottom
width=65%
height=100%
group=2.Cover customization
:i2 refid=customization.Cover creation
:p.
When creating a cover for a CD the classes open Photo Graphic PRO with a cover template. These templates may be
changed to fit your needs. You'll find them in the :hp2.bin:ehp2. directory of the Audio/Data-CD-Creator installation
directory.
:p.
:ul.
:li.:hp2.back.cwx:ehp2. for audio CDs
:li.:hp2.databack.cwx:ehp2. for data CDs
:eul.
:p.
The data template does nothing special but the audio template is more advanced. When creating a cover for
audio CDs the wave names and the ID3 tag information of MP3 files are copied to the end of the template. This way
you may create a cover in just a few seconds holding all the titles of your CD.

