:h2 res=571
x=right y=bottom
width=65%
height=100%
group=2. Create a cover sheet
:i1.Cover sheet
There's support for automatic cover sheet creation. Select the menu item :hp2.Create cover:ehp2. to do so.
A REXX script will be created in the folder which is usable with Photo Graphics PRO. If P>G PRO
is properly installed a double klick launches the program and creates a sheet with the names of the
tracks in the folder and the playtime for each track. If MP3 files carry an ID3 tag the information about
the file will be taken from this tag and placed in the sheet.

:note.The template for the REXX skript is the file :hp2.back.cwx:ehp2. for audio cds and :hp2.databack.cwx:ehp2. for data cds in the bin directory. It contains the
draw commands for P>G PRO. You may adapt this file to fit your needs. All track information is added
at the end of this file when creating the skript.

:note.Get Photo>Graphics PRO from
:link reftype=launch
object='netscape.exe'
data='http://hobbes.nmsu.edu'.
http&colon.//hobbes.nmsu.edu:elink.

:note. As Truespectra has ended all support for Photo Graphics Pro (not only the OS/2 version but also the
windows release) and even say they never had any OS/2 products at all the program and the free registration 
key may no longer be downloaded from their site because the webpages are no 
longer online. The following is the free registration key from the homepage&colon. TSPG20-000K-65WG8.

:note.CD-Covers can be obtained here
:link reftype=launch
object='netscape.exe'
data='http://www.cdcovers.cc'.
http&colon.//www.cdcovers.cc:elink.