:p.
Thanks to the following persons who helped bringing Audio/Data-CD-Creator into shape:
:p.
:ul compact.
:li.Klaus Staedtler for the icons, the improvement of
the tutorial and helpfile and fearless beta testing.
:li.Arjen Meijer for creating the background pictures.
:li.M. Hipp for mpg123.
:li.Samuel Audet for his nice OS/2 port of mpg123. I only changed
a few lines to fix some problems with stdout, so all the credits belongs to him.
:li.Christian Hennecke for several bugfixes to the install script.
:li.Alexander Wittig for some patches correcting problems with spaces and
 the author name, preparer etc.
:li.dink for adding some special options to z! (visit http&colon.//dink.org for more) so
it seemlessly integrates into Audio-CD-Creator.
:li.Christoph Kloeters for improvements to the PGP>Pro cover scripts.
:li.Kris Buelens for error correction in one of the DrDialog helpers.
:li.Ron Gemeinhardt. I took the book icon from his Free-D Warp icons package (can be found on Hobbes).
:li.All the users who sent in bug reports and feature suggestions.
:eul.
:p.





