:h1 res=5400.Help for DAO writing
:p.
Specify the settings for DAO writing on this dialog. The write parameters
are taken from the CD-Creator settings notebook but may be adjusted if
necessary. You may adjust the pregap of each track by selecting the corresponding
item from the popup menu of the track. Be sure to read the chapter about
pregaps in the tutorial first.
:p.
If any wave file is tagged as not valid the format isn't correct. Files
to be written on CD must be 44.1kHz/2 Channels/16bit.
:p.
You may save the resulting TOC file for later use or editing. If you
want to do so choose the item from the context menu.

:nt.
If you want to write MP3 (Ogg, AIFF...) files in DAO mode you must select the
MMIO procedures as decoders on the MP3 decoder page of the main settings notebook. 
Be sure you have installed the appropriate procedure and the times shown are
correct. Read the MP3 writing chapter in the tutorial if in doubt.
:ent.


