:p.
Put all the files and directories you want to burn on CD into this folder. You don't have to
make copies of your files. Create a virtual tree of shadows to save some space.
Select the action you want to perform on the left side of the window. 
.br
You may
create an image file only, write an already created image on CD or even create a CD on the fly.
:p.
 For further information select one of the items below:
:p.
:link reftype=hd res=1610.Create image only:elink.
:p.
:link reftype=hd res=1611.Write only:elink.
:p.
:link reftype=hd res=1612.On the fly:elink.
:p.
:link reftype=hd res=1607.Check size:elink.
:p.
:link reftype=hd res=226.Test only:elink.
:p.
:link reftype=hd res=1501.Imagename:elink.
:p.
:link reftype=hd res=1502.Browse:elink.
:p.
:link reftype=hd res=1503.Toolbar:elink.
