:h2 res=150
x=right y=bottom
width=75%
height=100%.Features
:p.Audio/Data-CD-Creator consists of WPS classes acting as frontends for the programs
which actually burn the CD. There're several unique features you don't find in any other OS/2
CD writing application.

:ul.
:li.Full integration into the WPS. Use the classes like any other folder on your system
:li.Use shadows for creating a virtual tree of files or putting together an audio sampler
:li.On the fly writing
:li.Image creation
:li.Creation of TAO and DAO Audio CDs
:li.DAO for audio CDs using cdrdao/2 with dynamic priority control
:li.Writing of any audio file known to OS/2 (MP3, Ogg, AIFF...)
:li.Direct creation of audio CDs using MP3 files
:li.Decoding of MP3 files
:li.Encoding of wave files to MP3 files
:li.On the fly encoding of CD tracks to MP3 files
:li.Support for any textmode grabber
:li.Tracktitle querying from FreeDB servers
:li.Creation of single- and multisession data CDs
:li.Support for mounting imagefiles
:li.Help for most functions. Use the help button or the right mouse button.
:eul.

:p.BTW you don't have to fear WPS crashes. The CD creation runs as a different process so
there's no influence and your CD will :hp2.not:ehp2. be corrupted.

