:h2 res=2010.User interface
:p.
Folder hints are shown if the pointer isn't moved for some seconds. They only pop up over
whitespace. Use the checkbox to disable or enable them.
:p.
Tips are shown when opening a creator folder. They only pop up once after the
system is started. There's an object in the CD-writing folder to manually open
the tip dialog.
:p.
With V0.51 the folders may have a new look. If you prefer the standard OS/2
look select the check box.

