
:h1 res=5000.Mount ISO imagefile dialog
:p.
You may mount an ISO imagefile on a free drive letter using the ISOFS filesystem. After doing so the
files written to the image are accessible like files on a CD. Note that currently only singlesession images
with Joliet names are supported.
:p.
Get further information by selecting the following items:
:ul.
:li.:link reftype=hd res=5006.Imagefile:elink.
:li.:link reftype=hd res=5009.Browse:elink.
:li.:link reftype=hd res=5004.Drive letter:elink.
:li.:link reftype=hd res=5005.Mount:elink.
:eul.

:h2 res=5006.Imagefile entry field
:p.
Insert the name of the imagefile you want to mount into this entry field or use the
:link reftype=hd res=5009.Browse:elink. button. Make sure a full name including the drive letter is given.

:h2 res=5009.Browse button
:p.
Use the browse button to find an imagefile to mount.

:h2 res=5004.Drive letter
:p.
This drop down box is filled with the currently free drive letters.

:h2 res=5005.Mount button
:p.
Pressing this button will mount the chosen imagefile on the selected drive letter. 

:h1 res=5100.Unmount ISO imagefile dialog
:p.
Use this dialog to unmount a previously mounted imagefile. The listbox only contains drives
with mounted imagefiles.

:p.
Get further information by selecting the following items:
:ul.
:li.:link reftype=hd res=5105.Drive listbox:elink.
:li.:link reftype=hd res=5106.Unmount:elink.
:eul.

:h2 res=5105.Drive listbox
:p.
This listbox contains all the drive letters with mounted imagefiles. Select a drive and
press :link reftype=hd res=5106.Unmount:elink. to unmount the image.

:h2 res=5106.Mount button
:p.
Press this button to unmount the image selected in the drive listbox.
