:h2 res=851
x=right y=bottom
width=65%
height=100%
group=2.Launch area
:i2 refid=customization.Launch area
:p.
Beside the toolbar to access frequently used objects and functions of the CD-Creator package there's
an additional launch area where you may drop any object.
:p.
:artwork  name='launchpad.bmp'.
:p.
This area behaves like the well known launchpad. There is one set of objects for audio-folders and
another for data-folders.
:p.

:nt.To remove an object select the delete item from the popup menu.:ent.

