:p.
The Main window divides into four parts. 
:ul.
:li.The container behaves like any WPS-folder container. You can put objects into it as usual. But only wavefiles
and shadows of wavefiles are considered when writing CDs. So you can put documentation files into the folder to
keep all parts of a project together.

:li.At the top of the window you can switch between :link reftype=hd res=601.write-:elink. and 
:link reftype=hd res=602.grab-mode:elink.. When in grab-mode an entryfield pops up
where you can enter the name for the saved tracked.
:li.The Toolbar gives you access to several tools, settings etc. You can also drop 
any preferred program into the empty button.
:li.On the left side of the window you can change options for the selected mode. According to your mode selection
this part changes.  
:eul.
