.**** Help panels for menus ****
:h1 res=6601.CD/RW-Tools menu
:p.
Select this menu to show a dialog which gives you access to some functions helping you when working with
CD-Rs or CD-R/Ws. For example loading and unloading the media, blanking, showing the ATIP 
informations on your CDR etc.

:h1 res=6613.Create cover menu
:p.
Select this menu to start Photo Graphics PRO with a template for a CD cover. If P>G PRO isn't
properly installed the template will be opened in E.EXE.
:p.
The Audio-CD template is prefilled with the tracknames and play times of the waves and MP3s of the folder.

:h1 res=6615.Help for ISOFS menu
:p.
This menu contains items dealing with the ISOFS filesystem. You may mount or unmount isoimages to check
the contents of the files.

:h1 res=6616.Help for mount ISO imagefile menu
:p.
This menu opens a dialog to mount an ISO image file on a free drive letter using the ISOFS filesystem. The path will be
taken from the image name entry field but you may change it later on using the dialog.
After mounting you may access the files in the image as if they were on CD.

:h1 res=6617.Help for unmount ISO imagefile menu
:p.
Using this menu you may unmount a previously mounted ISO imagefile. A dialog will pop up where you
may select the drive you want to unmount.

:h1 res=6618.Help for MP3 decoding menu
:p.
Selecting this menu will open a dialog for decoding MP3 files.
:p.
Only files which are selected in the folder will be used. The decoded files will be
placed into the folder.

:h1 res=6619.Help for wave file encoding menu
:p.
Selecting this menu will open a dialog for the encoding of wave files to MP3 files.
:p.
Only files which are selected in the folder will be used. The encoded files will be
placed into the folder. Make sure LAME is installed. This MP3 encoder may be found on
Hobbes (http&colon.//hobbes.nmsu.edu). Use version 3.93.1 or above. Other releases may work but that's
not tested.







