:h2 res=551
x=right y=bottom
width=65%
height=100%
group=2.Mounting the ISO imagefile
:i1 roots='mount isoimage'.Mounting an ISO file
:i2 refid=isoimage.Mounting
:p.
If ISOFS an installable filesystem for accessing ISO imagefiles is installed an imagefile may
be mounted on any free drive letter. This filesystem is included in the full package of
Audio/Data-CD-Creator or may be downloaded here:
:p.
:link reftype=launch
object='netscape.exe'
data='http://www.geocities.com/SiliconValley/Sector/5785/index.html'.
http&colon.//www.geocities.com/SiliconValley/Sector/5785/index.html:elink.
:p.
:link reftype=launch
object='netscape.exe'
data='http://www.os2world.com/cdwriting'.
http&colon.//www.os2world.com/cdwriting:elink.

:p.
Data-CD-Creator automatically detects if the FS is installed and an additional menu will be
inserted in the menubar of a data folder. Use the menu items to mount or unmount an imagefile.
:p.
:artwork align=center name='mountiso.bmp'.


:nt.
Currently (as of V0.2.1 of the filesaystem) only Joliet names are supported. 
:ent.