:h1 res=5300.MP3 decoding
:p.
This dialog opens after selecting some MP3s in the audio folder
and choosing the :hp2.Decode MP3 files...:ehp2. menu. The listbox
shows the MP3 files with further information. By doubleclicking
a file it will be played using z! or the MMIOMP3 codec. The context 
menu lets you query the ID3 tag information.
:p.
Press the :hp2.Decode:ehp2. button to start the decoding. Statusbars
show the progress.



