:h1 res=5600.MP3 encoding
:p.
This dialog opens after selecting some wavess in the audio folder
and choosing the :hp2.Encode wave files...:ehp2. menu. The listbox
shows the wave files selected in the folder.
:p.
Press the :hp2.Encode:ehp2. button to start the encoding. The
quality settings for LAME are taken from the main Audio-CD-Creator
settings notebook. You may stop the wave encoding at any time.




