:h1 res=020.CD writing tutorial
:i1 global.CD writing tutorial
:p.
The CD writing tutorial describes all the steps for successfully writing CDs.
It covers the creation of singlesession and multisession data CDs, image building, creation of audio CDs, MP3 writing, customizing the programs and much more.

:h1 res=021.CD-writing utilities
:i1 global.CD writing utilities
:p.
The CD writing utilities folder is the main place for every CD writing related utility.
It contains objects for the different tasks like CD copy or data CD creation.
Pointers to the documentation of the different program used for writing
help you finding necessary information. Using the 
:link reftype=hd res=003.CD-Creator Settings:elink. object
and the configuration folder you may customize your setup.  

:h1 res=022.CD-Copy
:i1 global.CD-Copy
:p.
Use the CD-Copy object to create a 1&colon.1 copy of a CD. This program
is a frontend shielding you from the syntax of cdrdao which actually does the work.

:h1 res=023.CDR-Tools
:i1 global.CD-Tools
:p.
The CD-Tools object opens a dialog where you may perform some common tasks
like CD-RW blanking, closing a CD or showing the contents on the track level.

:h1 res=024.Configuration and (Un)Installation
:i1 global.Configuration and (Un)Installation
:p.
The Configuration and (Un)Installation folder contains objects to customize
your Audio/Data-CD-Creator setup. An object is provided for the recreation
of lost WPS objects.

:h1 res=025.Recreate WPS-objects
:p.
Use Recreate WPS-objects to rebuild the objects of Audio/Data-CD-Creator if
you have lost any of them. Objects already existant will be preserved. 
