
:h1 res=5720.On the fly encoding 
:p.
Specify the location where you want to place the encoded files using this dialog. 
You may choose to place the files in the folder from which this dialog was opened or into
your MP3 library.
The path to the library is taken from the main settings notebook. The library is a directory
in which for every artist a subdirectory tree will be built and populated with the tracks of
this particular artist.
.br
Note that the :hp2.Destination:ehp2. entry field shows the whole path which already contains
the subdirectories for this particular CD. It's not the base path of your MP3 library. 
:p.
:nt.
To get automatically the tracknames from a FreeDB server you have to provide some
information on the FreeDB page of the main settings notebook. For setting the
ID3 tag of the MP3 file the CW-multimedia classes V0.2.5 or above must be installed.
Get them from the URL below.    
:p.
:link reftype=launch
object='netscape.exe'
data='http://www.os2world.com/cdwriting'.
http&colon.//www.os2world.com/cdwriting/:elink.
:ent.

:p.
If track data can't be queried from the FreeDB server you may alternatively specify the album title
and the artist name here. Tracks will be named Track 01, Track 02 etc. then.
:p.
Press the :hp2.Encode:ehp2. button to start the encoding. 


:h1 res=5700.On the fly encoding status 
:p.
This dialog shows the current encoding status when performing on the fly
encoding of CD tracks to MP3 files.
:p.
You may cancel the encoding at any time. Note that the current track will always be finished.
Progress bars show the status of the track encoding and the overall progress.
You may notice that the :hp2.Break:ehp2. button is disabled after cancelling the process.
When encoding of the current track is finished a :hp2.Done:ehp2. button enables
you to dismiss the dialog.

