:h2 res=503
x=right y=bottom
width=65%
height=100%
group=2.Creating singlesession CDs
:i1.Singlesession
:note.You can't append data to a CD which is written in singlesession mode no matter
how small this first (and only) session is.

:ol.
:li.Open the CD-writing folder.
:li.Drag the :hp2.Create data CD:ehp2. template somewhere and drop it in your file system. A new Data-CD-Creator folder will be created. Open this new folder by double clicking it.

:li.Open the settings notebook and select :hp2.singlesession:ehp2..

:li.If you've already created an image (see :link reftype=hd res=501.Creating an image file:elink.) close
the settings notebook and write this file on the CD:

:ul.
:li.Select :hp2.Write image:ehp2. and insert the filename into the entry field. You also may use the
:hp2.Browse:ehp2. button to find the source image.

:li.Click :hp2.Write CD:ehp2. to write the image to the CD.

:li.You're done.
:eul.

:li.If you want to write on the fly then select on the filename page how filenames are written on the CD. If you want to create a
CD readable with plain DOS you have to leave :hp2.-l:ehp2. unchecked so an
image with 8.3 names is created. The other options shouldn't do any harm.

:li.Fill in the information about the CD on the next page of the notebook. Close the notebook.

:li.Put all the files and folders you want to burn into the folder. You may also use shadows.
Data-CD-Creator will follow them and write the shadowed filesystem objects on the CD. If you've set
the right option on the :hp2.Special:ehp2. page of the folder settings notebook you may create a virtual
tree of files using shadows inside of shadow folders.

:li.Click :hp2.Write CD:ehp2. to write the CD.

:eol.