:h3 hide res=2100.Tracklist window
:p.
Check the order of your tracks here.
:p.
E.g. if you want to burn a complete audio-cd you have to select after grabbing 
'sort by name' otherwise the CD will start with the last track.
:p.
You may get some information about the format of the tracks by doubleclicking
on an entry of the listbox. 
:p.
If you use :hp2.TAO:ehp2. (track at once) writing there will be a pause of 2 seconds after
each written track. There's no way around this because the writer inserts it according
to the audio-CD standard. If you want to write audio-CDs without this pause use :hp2.DAO:ehp2.
(disc at once) instead.
