:h2 res=407
x=right y=bottom
width=65%
height=100%
group=2. Use two cd-writers at the same time

:ol.
:li.Drag and Drop a second 'Create Audio CD template' into your filesystem.
:li.All other steps are identical to the ones using only one writer with one 
exception&colon. When you press 'write' you have to select your second 
writer in the write-window.
:artwork name='writeaudio.bmp'.
:li.You can't burn the same session at two recorders at the same time (no 
parallel recording).
:li.If you want to copy the same tracks at the same time on two recorders 
you have to copy all grabbed files from the 'Create Audio-CD' Folder 1 to 
your 'Create Audio-CD' Folder 2.
:eol.

