:h2 res=302
x=right y=bottom
width=65%
height=100%
group=2. Upgrade from an older version.
:p.
:ol.
:li.Uninstall the previous version using the Generic Installer (or the uninstall.cmd with older versions) coming with that release. 
Restart the WPS.
:li.Sometimes it may be necessary to clean the OS2.INI and/or the templates folder.
:li.Check if the file aucdfldr.hlp is deleted from the system help directory x&colon.\os2\help. This check is necessary because the file may be locked during uninstallation so deletion fails. 
:li.Unzip the distribution into a folder of your choice.
:li.Copy the cdrecord.ini file from your old installation into the directory of the new release.
:li.Run Install.exe which in turn starts a graphical configuration program. All your settings are preserved and you can check them on the
configuration pages. Press Finish to install the new version of the classes. The WPS classes will
be registered and the CD-Writing folder recreated on the desktop.
:li.Check the settings and use also the 'help' button cause there might be additional settings and 
informations, which weren't in former releases.
:eol.