:h2 res=402
x=right y=bottom
width=65%
height=100%
group=2. Using grabbing to create an audio CD
:i1.Grabbing
:ol.
:li.Open the CD-writing folder.
:li.Drag the :hp2.Create audio CD:ehp2. template somewhere and drop it in your file system. A new Audio-CD-Creator folder will be created. Open this new folder by double clicking it.
:li.Select the :hp2.Grab:ehp2. radio button. The folder switches into grab mode.
:li.Press :hp2.Refresh:ehp2. to fill the listbox with the tracks of the inserted CD.
:li.Select the tracks you want to grab and enter a filename into the entryfield. 
If you have CDDB enabled no filename is necessary.
:artwork name='grabmode.bmp'.
:li.Press :hp2.Grab:ehp2. to start grabbing. A status window pops up and the tracks will be written
into the folder.
:li.After end of grabbing, order the waves as desired (e.g. for copying a whole Music-CD select 'sort by name' 
to have all tracks appearing in the order they are on the Original-CD). Doing a 
double-click one the track starts the wav-player. Doing a right-click and select 
'open' gives you a menue with several options, e.g. start the wave-player or the 
wave-editor. The player as the editor are the standard mmos2 components.
:li.Now select the write options and press :hp2.Write:ehp2.. If you're uncertain about the meaning of the 
write options use the right mouse button to get help.
:li.When pressing 'write' a window opens
:artwork name='writeaudio.bmp'.
showing some informations like the size of all files together, the recording time. All selected files are listed. 
Here you can too select an alternative cd writer instead of the default one select during install.
:li. Double-clicking on a file shows you informations about the file
:artwork name='waveinfo.bmp'.
:eol.

:note.Depending on your grabber tracknumbers will be appended to the name automatically. If your
grabber does not support this you may check :hp2.Add tracknumbers:ehp2. on the grabber page
of the Creator-settings object.

:note.There's no check for duplicate filenames. So be careful not to overwrite wave files.

:note.You may put other files like text files into the folder, too. Audio-CD-Creator skips these
files when creating the CD.
