:h2 res=502
x=right y=bottom
width=65%
height=100%
group=2.Writing an existing image file
:i1 roots='image'.Writing an image file
:ol.
:li.Open the CD-writing folder.
:li.Drag the :hp2.Create data CD:ehp2. template somewhere and drop it in your file system. A new Data-CD-Creator folder will be created. Open this new folder by double clicking it. You may also use
an already existing Data-CD-Creator folder.

:li.Open the settings notebook by clicking :hp2.CD-Settings...:ehp2. and select the type of CD
you want to create (singlesession or multisession). Be sure the image was created the right way if you
want to write an image as a multisession CD. Only the image for the first session may be created like a singlesession CD. Any
image for a following session must be created with the multisession option set.
See :link reftype=hd res=501.Creating the image file:elink. for more information about image creation.


:li.Select :hp2.Write image:ehp2. and insert the filename into the entry field. You also may use the
:hp2.Browse:ehp2. button to find the source image.

:li.Click :hp2.Write CD:ehp2. to write the image to the CD. A status dialog pops up showing the amount of data
already written.

:note.You may also use an already existing iso-image (e.g. from a linux distribution). These images which are
often downloadable from the internet are usually single session images.

:eol.

