:h2 res=403
x=right y=bottom
width=65%
height=100%
group=2. Using shadows to create an audio sampler
You may already have some wave files on your disk grabbed in the past. If you want to put
together a sampler containing these waves you don't have to copy them into one Audio-CD-Creator
folder. Just use shadows to link them together. You may mix shadows and real files in any order.

:ol.
:li.Open the CD-writing folder.
:li.Drag the :hp2.Create audio CD:ehp2. template somewhere and drop it in your file system. A new Audio-CD-Creator folder will be created. Open this new folder by double clicking it.
:li.Put together your sampler by using shadows of wave files (you also may use real wave files).
:li.Order the tracks as desired and press :hp2.Write:ehp2. after selection of the write options. If you're uncertain about the meaning of the write options use the right mouse button to get help.
:artwork name='writeshadow.bmp'.
:eol.

:note.You may put other files like text files into the folder, too. Audio-CD-Creator skips these
files when creating the CD.
