# Makefile for Audio-CD-Creator Data-CD-Creator

include ../make.inc

ODIR		= ./obj

all: cfgdata.ini

cfgdata.ini:	drivedata.txt
		create_cfgdata_ini.CMD cfgdata.ini

clean:
	-rm cfgdata.ini

cleaner:
	-rm *.*~

distribution:

	
