# Makefile for Audio-CD-Creator Data-CD-Creator

include ../make.inc

CC           = icc
LIB_DIR      = $d:/emx/lib 
CPPFLAGS     = /Ge- /Gm+ /G4 /Gl  /O+ /Oc+ /Ol- /Q+ $(VACDEBUG)
INC	=	..\include
DEFS         = 
PROGS        = 
ODIR		= ./obj
CPPDIR	= .
BINDIR		=	../../dist
RES		=	..\res


OBJECTS	=  


all:	
#$(OBJECTS)
	cd ../creator && make

#datacdfolder.obj:	datacdfolder.cpp $(INC)\audiofolder.hh $(INC)\audiofolderres.h
#	icc $(CPPFLAGS) /C+ -I$(INC) $<

#datadialogprocs.obj:	datadialogprocs.cpp $(INC)\audiofolderres.h $(INC)\audiofolder.hh $(INC)\launchpad.hh
#	icc $(CPPFLAGS) /C+ -I$(INC) $<

#dataoverriddenwpclsmethods.obj:	dataoverriddenwpclsmethods.cpp $(INC)\audiofolderres.h $(INC)\audiofolder.hh
#	icc $(CPPFLAGS) /C+ -I$(INC) $<

#dataoverriddenwpmethods.obj:	dataoverriddenwpmethods.cpp $(INC)\audiofolderres.h $(INC)\audiofolder.hh
#	icc $(CPPFLAGS) /C+ -I$(INC) $<

#datasettingsprocs.obj:	datasettingsprocs.cpp $(INC)\audiofolderres.h $(INC)\audiofolder.hh $(INC)\launchpad.hh
#	icc $(CPPFLAGS) /C+ -I$(INC) $<

clean:
	-rm *.obj

cleaner:
	-rm *.*~
	-rm *.flc


distribution:


	
